### ISSUE TITLE
I am trying to do the below task but still my rds snapshot can not be stored in s3.

### ISSUE THREAD

**Issue by eddamalique01** [cloudyr/aws.lambda#6]
Lambda function to take snapshot or backup of RDS database and store in S3

My IAM policy:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "rds:CreateDBSnapshot"
            ],
            "Resource": "arn:aws:rds:us-west-1:923903436004:db:*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObjects",
                "s3:ListBuckets"
            ],
            "Resource": "arn:aws:s3:::maurice-rdsbackup-bucket"
        }
    ]
}

and the lambda function:

import boto3
import datetime
#connecting to the RDS database
def lambda_handler(event, context):
    print("Connecting to RDS")
    client = boto3.client('rds')
#creating the database snapshot 
    print("RDS snapshot backups started at %s...\n" % datetime.datetime.now())
    client.create_db_snapshot(
        DBInstanceIdentifier='maurice-testdatabase-instance', 
        DBSnapshotIdentifier='mauricesnapshot2',
        Tags=[
            {
                'Key': 'name',
                'Value': 'my-test-database'
            },
        ]
    )
    
    print("saving snapshot to S3 bucket")
    s3 = boto3.resource("s3")
    s3.Object("maurice-rdsbackup-bucket", "DBSnapshotIdentifier").upload_file("DBSnapshotIdentifier")

**Comment by leeper** [comment]
Your question is about [boto3](https://github.com/boto/boto3), not this package.
