### ISSUE TITLE
Seeking new maintainer!

### ISSUE THREAD

**Issue by leeper** [cloudyr/aws.lambda#8]
This package is not being actively maintained. If you're interested in contributing or taking over, please express your interest here.

**Comment by jonthegeek** [comment]
If @s-u isn't able to maintain this one, I'll take it. It looks like everything this package imports or suggests is already resurrected, thankfully. @MarkEdmondson1234 I'll take this one.

**Comment by MarkEdmondson1234** [comment]
Thanks @jonthegeek !

**Comment by s-u** [comment]
Please, go ahead, great, thanks @jonthegeek!

**Comment by jonthegeek** [comment]
It's working over in #11! I'm going to do a bit more before resubmitting to CRAN (and, of course, I need to be able to merge before that) to make sure it REALLY works, but so far so good!

@s-u Is there anywhere we can easily talk to coordinate things (such as a Slack)? No biggy if that doesn't work for you, but I think this will have a lot of similarity with aws.s3, and I don't want to drift TOOO far from the same "feel." You can usually find me at r4ds.io/join (the R4DS Online Learning Community slack), or maybe there's a cloudyr team slack, or... ?

**Comment by jonthegeek** [comment]
Oh, I didn't see the invitation come in! Looks like it's official!

**Comment by MarkEdmondson1234** [comment]
There is a cloudyr Slack that has never been used, but if there is demand I can send some invites

**Comment by s-u** [comment]
Sure, that would be great! I think we need to synchronize across the packages ...

**Comment by MarkEdmondson1234** [comment]
Ok I've set up a form to collect the Slack invite emails: https://forms.gle/GhZoRqLQLcSjcmYh9

**Comment by jonthegeek** [comment]
@MarkEdmondson1234 we're set up on the r4ds slack, so, for now, I'd prefer that, for two reasons:
* I'm always there, and
* I've been working on setting up "project" channels on that slack to teach people to contribute to open source. 

I won't open it up to everyone when we first start, but it might be a natural way to get more contributors and avoid burnout. 

What do you think?

**Comment by s-u** [comment]
@jonthegeek I would strongly prefer using cloudyr Slack.

**Comment by jonthegeek** [comment]
@s-u OK, no prob!

**Comment by MarkEdmondson1234** [comment]
Ok invites sent, lets try it out.  @jonthegeek I am in several slack groups with the desktop client and its not much both switching between them - set up notifications as you like it etc.  I anticipate for now it will be low traffic and only for maintainers of cloudyr to coordinate - once you are signed up I'll give you access to accept/make invitations from there to add anyone else who would like to be in there. Perhaps after a while it can be a chat support for cloudyr packages, I find it useful for the googleAuthR packages to have an informal way to chat before its a github issue.
